##
## EPITECH PROJECT, 2023
## Untitled (Workspace)
## File description:
## Makefile
##

NAME = solver

all: $(NAME)

$(NAME): $(LIBRARY_NAME)
	cp $(NAME).py $(NAME)
	chmod +x $(NAME)

fclean:
	rm -f $(NAME)

re: fclean all

.PHONY: build fclean re
